words = [
    "APIKEY",
    "Abandonware",
    "Betroffenenrechte",
    "Buildx",
    "CAROOT",
    "CSIC",
    "CTAN",
    "Cascadia",
    "Consolas",
    "DSGVO",
    "Dailymotion",
    "Dexie",
    "Ecosia",
    "Eurogamer",
    "HCAPTCHA",
    "Hohenems",
    "INITDB",
    "Kotaku",
    "Metacritic",
    "Nußbaumer",
    "PGDATA",
    "PKCS",
    "Presigned",
    "Qwant",
    "Searchalot",
    "Sohlstraße",
    "Supportanfragen",
    "Swisscows",
    "Usec",
    "Vite",
    "Wickenburggasse",
    "atlaskit",
    "autosize",
    "bowser",
    "bubblewrap",
    "buildx",
    "bunx",
    "cascadia",
    "changefreq",
    "choco",
    "ciphernotes",
    "ciphertext",
    "clientside",
    "clipb",
    "comlink",
    "createdb",
    "customtabs",
    "dasharray",
    "dashoffset",
    "datname",
    "dexie",
    "dockerhub",
    "dockerimage",
    "downl",
    "esnext",
    "genkeypair",
    "genpkey",
    "github",
    "hcaptcha",
    "healthcheck",
    "hitbox",
    "impressum",
    "inet",
    "isready",
    "jarfile",
    "jose",
    "jszip",
    "keyalg",
    "keymap",
    "keypair",
    "keysize",
    "keytool",
    "lastmod",
    "levenshtein",
    "linecap",
    "linejoin",
    "linux",
    "mailjet",
    "mantine",
    "matplotlib",
    "navigatable",
    "nginx",
    "nocrypt",
    "nvmrc",
    "openssl",
    "outdir",
    "outform",
    "panzoom",
    "passwortloser",
    "pgsty",
    "pkcs",
    "pkeyopt",
    "postgres",
    "postgresql",
    "precache",
    "precaching",
    "presign",
    "presigner",
    "printcert",
    "psql",
    "pubout",
    "qrcode",
    "rapnuss",
    "replit",
    "rgba",
    "rolname",
    "sels",
    "serverside",
    "serviceworker",
    "stackexchange",
    "tabler",
    "topk",
    "unarch",
    "urlset",
    "uuid",
    "uuidv",
]
min_word_length = 4
